frontend:
  image:
    repository: "322686612450.dkr.ecr.ap-south-1.amazonaws.com/three-tier-frontend"
    tag: "latest"
backend:
  image:
    repository: "322686612450.dkr.ecr.ap-south-1.amazonaws.com/three-tier-backend"
    tag: "latest"

database:
  password: "Suren@7712"
