frontend:
  image:
    repository: "322686612450.dkr.ecr.ap-south-1.amazonaws.com/three-tier-frontend"
    tag: "791860af2aacf9fb8d97bfb3ccd7c881f5ec029d"
backend:
  image:
    repository: "322686612450.dkr.ecr.ap-south-1.amazonaws.com/three-tier-backend"
    tag: "791860af2aacf9fb8d97bfb3ccd7c881f5ec029d"

database:
  password: "Suren@7712"
