apiVersion: v1
kind: Service
metadata:
  name: {{ include "three-tier-app.fullname" . }}-backend
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "three-tier-app.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
