apiVersion: v1
kind: Secret
metadata:
  name: {{ include "three-tier-app.fullname" . }}-db
  namespace: three-tier
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
  database: {{ .Values.database.database | quote }}
