apiVersion: v1
kind: Service
metadata:
  name: {{ include "three-tier-app.fullname" . }}-frontend
  namespace: three-tier
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "three-tier-app.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
