apiVersion: v1
kind: Service
metadata:
  name: {{ include "three-tier-app.fullname" . }}-postgres
  namespace: three-tier
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "three-tier-app.name" . }}
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
